config/routes.rb
Ygexoticherbs::Application.routes.draw do

  resources :mailing_lists, :only => [:create]
  get "/name_and_email" => "mailing_lists#new", :as => "name_and_email"

  resources :carts, :only => [:new, :create, :edit, :update] do
    member do
      get :confirm_orders
      post :confirm_orders
      get :thanks_for_order
    end

    collection do
      get :sign_in
      post :sign_in
    end
  end

  namespace :admin do
    resources :products
    resources :users
    resources :carts
    resources :orders
  end

  resources :users, :only => [:new, :edit, :create, :update]
  resources :user_sessions
  resources :products, :only => [:index, :show]
  resources :user_email, :only => [:new, :create]

  root :to => "pages#welcome"
  get "/home" => "pages#welcome", :as => "welcome"
  
  get "/contact-us" => "pages#contact_us", :as => "contact_us"

  get "/about-us" => "pages#about_us", :as => "about_us"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :username, :email, :cart_total, :cart_quantity, :address1, :address2, :province, :zip_code, :telephone_number, :user_id, :cart_id, :product_id, :product_name, :status
  
  validates_presence_of :email
  validates_presence_of :cart_total
  validates_presence_of :cart_quantity
  validates_presence_of :address1
  validates_presence_of :address2
  validates_presence_of :province
  validates_presence_of :zip_code
  validates_presence_of :telephone_number

  has_many :orders
  belongs_to :user
  belongs_to :mailing_list

end

app/controllers/admin/carts_controller.rb
class Admin::CartsController < ApplicationController
  # GET /admin/carts
  # GET /admin/carts.json
  def index
    @admin_carts = Admin::Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_carts }
    end
  end

  # GET /admin/carts/1
  # GET /admin/carts/1.json
  def show
    @admin_cart = Admin::Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_cart }
    end
  end

  # GET /admin/carts/new
  # GET /admin/carts/new.json
  def new
    @admin_cart = Admin::Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_cart }
    end
  end

  # GET /admin/carts/1/edit
  def edit
    @admin_cart = Admin::Cart.find(params[:id])
  end

  # POST /admin/carts
  # POST /admin/carts.json
  def create
    @admin_cart = Admin::Cart.new(params[:admin_cart])

    respond_to do |format|
      if @admin_cart.save
        format.html { redirect_to @admin_cart, notice: 'Cart was successfully created.' }
        format.json { render json: @admin_cart, status: :created, location: @admin_cart }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/carts/1
  # PUT /admin/carts/1.json
  def update
    @admin_cart = Admin::Cart.find(params[:id])

    respond_to do |format|
      if @admin_cart.update_attributes(params[:admin_cart])
        format.html { redirect_to @admin_cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/carts/1
  # DELETE /admin/carts/1.json
  def destroy
    @admin_cart = Admin::Cart.find(params[:id])
    @admin_cart.destroy

    respond_to do |format|
      format.html { redirect_to admin_carts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :require_login, :except => [:sign_in]

  def sign_in
    @user_session = UserSession.new
    @prod_id = params[:product_id]
    if request.post?
      @user_session = UserSession.new(params[:user_session])
      if @user_session.save
        redirect_to new_cart_path(:product_id => @prod_id)
      else
        flash[:error] = "An error has occurred while trying to sign you in"
      end
    end
  end

  def new
    @cart = Cart.new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @product = Product.find(params[:cart][:product_id])
    @current_user = current_user
    order_quantity = params[:cart][:order][:quantity].to_i
    total_price = @product.price * order_quantity
    @user_info = params[:cart]
    @user_info.delete_if { |k, v| (k == "order" || k == "product_id")}
    @user_info.merge(:user_name => @current_user.username, 
                     :email => @current_user.email, 
                     :status => "incomplete")
    @cart = Cart.new(:cart_total => total_price,
                     :cart_quantity => order_quantity,
                     :user_id => @current_user.id)
    @order = Order.new(:total => total_price,
                       :quantity => order_quantity,
                       :cart_id => @cart.id,
                       :product_id => @product.id,
                       :product_name => @product.name)
   @cart.update_attributes(@user_info)
   @order.update_attributes(@user_info)
   if @cart.save && @order.save
     redirect_to confirm_orders_path(@cart.id)
   else
     flash[:error] = "An error has occurred"
     render :action => :new
   end
    
  end

  def update
    @cart = Cart.find(params[:id])
  end

  def confirm_orders
  end

  def thanks_for_order
  end


  protected

  def require_login
    unless current_user #&& current_user.admin
      flash[:error] = "You must be logged in to access this page"
      #redirect_to products_path
      redirect_to sign_in_carts_path
    end 
  end
end

app/helpers/admin/carts_helper.rb
module Admin::CartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.haml
-#= f.inputs do
 -#= f.input

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/new.html.haml
%section.carts
  %h1= "Create your order"

  .order-creation
    = semantic_form_for @cart do |f|
      .product-info
        = image_tag("coming-soon-full.png", :class => "coming-soon-cart")
        %h3= "Product: #{@product.name} (#{@product.packaging_type})"
        %h3= "Price: #{number_to_currency(@product.price)}"
        = f.semantic_fields_for @order do |order_form|
          = order_form.input :quantity, :input_html => {:id => "quantity-spinner"}
      .customer-info
        = f.inputs do
          = f.input :address1
          = f.input :address2
          = f.input :province
          = f.input :zip_code
          = f.input :telephone_number
          = f.input :product_id, :value => params[:product_id], :as => :hidden
      .next-step
        = f.buttons do
          = f.commit_button "Go To Step Three"
        

app/views/carts/sign_in.html.haml
%section.carts

  %h1.must-sign-in= "You must be signed in to place an order"
  .sign-in
    = semantic_form_for @user_session, :url => sign_in_carts_path(:product_id => params[:product_id]) do |f|
      = f.inputs do
        = f.input :username
        = f.input :password
      = f.buttons do
        = f.commit_button "Submit"


    = link_to "Need an account? Get one here", new_user_path