config/routes.rb
Ygexoticherbs::Application.routes.draw do

  resources :mailing_lists, :only => [:create]
  get "/name_and_email" => "mailing_lists#new", :as => "name_and_email"

  resources :carts, :only => [:new, :create, :edit, :update] do
    member do
      get :confirm_orders
      post :confirm_orders
      get :thanks_for_order
    end

    collection do
      get :sign_in
      post :sign_in
    end
  end

  namespace :admin do
    resources :products
    resources :users
    resources :carts
    resources :orders
  end

  resources :users, :only => [:new, :edit, :create, :update]
  resources :user_sessions
  resources :products, :only => [:index, :show]
  resources :user_email, :only => [:new, :create]

  root :to => "pages#welcome"
  get "/home" => "pages#welcome", :as => "welcome"
  
  get "/contact-us" => "pages#contact_us", :as => "contact_us"

  get "/about-us" => "pages#about_us", :as => "about_us"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body

  acts_as_taggable
  has_ancestry :orphan_strategy => :rootify

  attr_accessible :name,
                  :slug,
                  :price,
                  :description,
                  :quantity,
                  :available,
                  :in_stock,
                  :packaging_type,
                  :scientific_name,
                  :recommendations,
                  :parent_id

  validates_presence_of :name, :message => "Please enter a name"
  validates_presence_of :slug, :message => "Please enter a slug"

  has_many :orders

  def to_param
    "#{id}-#{name.downcase.split.join("-")}"
  end

  def truncated_descript
    stripped_descrip = Sanitize.clean(description.strip, Sanitize::Config::RESTRICTED).split
    (stripped_descrip.length > 12) ? (stripped_descrip[0..11].join(" ") + "...") : stripped_descrip.join(" ")
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.roots.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "A new product has been created"
      redirect_to admin_products_path
    else
      flash[:error] = "There was a problem"
      render :action => :new
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.attributes = params[:product]
    if @product.save
      flash[:notice] = "The product has been updated"
      redirect_to admin_products_path
    else
      flash[:error] = "There was a problem updating this product"
      render :action => :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @browser_title = "All Products"
    @products = Product.roots.paginate(:page => params[:page], :per_page => 4).search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
    @browser_title = @product.name
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
= f.inputs do
  = f.input :name
  = f.input :scientific_name
  = f.input :slug
  = f.input :price
  = f.input :quantity
  = f.input :packaging_type
  = f.input :parent_id, :as => :select, :collection => options_from_collection_for_select(Product.roots, 'id', 'name', product.ancestry)
  = f.input :description, :as => :text, :input_html => { :class => 'ckeditor' }, :label => "Description"
  %br
  = f.input :recommendations, :as => :text, :input_html => { :class => 'ckeditor' }, :label => "Recommendations"
  = f.input :available, :as => :boolean
  = f.input :in_stock, :as => :boolean

app/views/admin/products/edit.html.haml
%section
  %h1= "Edit product"

  = semantic_form_for @product, :url => {:action => :update} do |f|
    -# = f.error_messages
    = render :partial => "form", :locals => {:product => @product, :f => f}

    = f.buttons do
      = f.commit_button "Edit"

app/views/admin/products/index.html.haml
%section
  %h1= "Product list"

  .index_products
    = link_to("Create Product", new_admin_product_path)
    - @products.each do |product|
      %table{:border => '2'}
        %tr
          %th.parent
            - sci_name = product.scientific_name.present? ? "(#{product.scientific_name})" : nil
            ="#{product.name}"
            = sci_name
            = link_to("Edit", edit_admin_product_path(product))
          %th.name="Name"
          %th.price="Price"
          %th.action="Actions"
        - product.children.each do |prod|
          %tr
            %td.parent
            %td.name= prod.name
            %td.price= number_to_currency(prod.price)
            %td.action= link_to("Edit", edit_admin_product_path(prod))
    

app/views/admin/products/new.html.haml
%section
  %h1= "Create a new product"

  = semantic_form_for @product, :url => {:action => :create} do |f|
    = f.error_messages  
    = render :partial => "form", :locals => {:product => @product, :f => f}

    = f.buttons do
      = f.commit_button "Create"

app/views/admin/products/show.html.haml
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>