config/routes.rb
Ygexoticherbs::Application.routes.draw do

  resources :mailing_lists, :only => [:create]
  get "/name_and_email" => "mailing_lists#new", :as => "name_and_email"

  resources :carts, :only => [:new, :create, :edit, :update] do
    member do
      get :confirm_orders
      post :confirm_orders
      get :thanks_for_order
    end

    collection do
      get :sign_in
      post :sign_in
    end
  end

  namespace :admin do
    resources :products
    resources :users
    resources :carts
    resources :orders
  end

  resources :users, :only => [:new, :edit, :create, :update]
  resources :user_sessions
  resources :products, :only => [:index, :show]
  resources :user_email, :only => [:new, :create]

  root :to => "pages#welcome"
  get "/home" => "pages#welcome", :as => "welcome"
  
  get "/contact-us" => "pages#contact_us", :as => "contact_us"

  get "/about-us" => "pages#about_us", :as => "about_us"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  acts_as_authentic

  attr_accessible :username,
                  :email,
                  :password,
                  :password_confirmation

  validates_uniqueness_of :username, :message => "This username is taken. Please use another"
  validates_presence_of :username, :message => "Please provide a username"
  validates_length_of :username, :in => 6..100, :message => "Your username is too short. Please provide a username that is more than 6 characters long"

  validates_uniqueness_of :email, :message => "An account already exists with this email"
  validates_presence_of :email, :message => "Please provide an email address"
  validates_format_of :email, :with => Authlogic::Regex.email, :message => "The email provided is not a valid format"
  validates_length_of :email, :in => 6..100, :message => "The email provided is too short"

  validates_presence_of :password, :message => "Please provide a password"
  validates_length_of :password, :in => 6..100, :message => "Your password must be longer than 6 characters long"

  validates_presence_of :password_confirmation, :message => "Please confirm your password"

  has_many :carts
  has_many :orders
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "A new user has been created"
      redirect_to admin_users_path
    else
      flash[:error] = "There was a problem"
      render :action => :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    if @user.save
      flash[:notice] = "The user has been updated"
      redirect_to admin_users_path
    else
      flash[:error] = "There was a problem"
      render :action => :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :only => [:edit, :update]
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Login successful"
      redirect_to products_path
    else
     flash[:error] = "There was a problem logging you in"
     render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    if @user.save
      flash[:notice] = "Your account has been updated"
      redirect_to products_path
    else
      flash[:error] = "There was a problem updating your account."
      render :edit
    end
  end

private
  def require_user
    unless @current_user.present?
      flash[:error] = "You must be logged in to view this page"
      redirect_to index_products_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= f.inputs do
  = f.input :username
  = f.input :email
  = f.input :password
  = f.input :password_confirmation

app/views/admin/users/edit.html.haml
%section
  %h1= "Edit User"

  = semantic_form_for @user, :url => {:action => :update} do |f|
    = f.error_messages
  
    = render :partial => "form", :locals => {:user => @user, :f => f}

    = f.buttons do
      = f.commit_button "Update"

app/views/admin/users/index.html.haml
%section
  %h1= "All Users"

  = link_to("Create User", new_admin_user_path) 

  - if @users.present?
    %table
      %tr
        %th= "Username"
        %th= "Email"
        %th
      - @users.each do |user|
        %tr
          %td= user.username
          %td= user.email
          %td= link_to("Edit", edit_admin_user_path(user))
  - else
    %p= "There are no users"

app/views/admin/users/new.html.haml
%section
  %h1= "Create new user"
  
  = semantic_form_for @user, :url => {:action => :create} do |f|
    = f.error_messages
    = render :partial => "form", :locals => {:user => @user, :f => f}

    = f.buttons do
      = f.commit_button "Create"

app/views/admin/users/show.html.haml
%section
  %h1= "Account for #{@user.name}"