config/routes.rb
Ygexoticherbs::Application.routes.draw do

  resources :mailing_lists, :only => [:create]
  get "/name_and_email" => "mailing_lists#new", :as => "name_and_email"

  resources :carts, :only => [:new, :create, :edit, :update] do
    member do
      get :confirm_orders
      post :confirm_orders
      get :thanks_for_order
    end

    collection do
      get :sign_in
      post :sign_in
    end
  end

  namespace :admin do
    resources :products
    resources :users
    resources :carts
    resources :orders
  end

  resources :users, :only => [:new, :edit, :create, :update]
  resources :user_sessions
  resources :products, :only => [:index, :show]
  resources :user_email, :only => [:new, :create]

  root :to => "pages#welcome"
  get "/home" => "pages#welcome", :as => "welcome"
  
  get "/contact-us" => "pages#contact_us", :as => "contact_us"

  get "/about-us" => "pages#about_us", :as => "about_us"
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body

  acts_as_taggable
  has_ancestry :orphan_strategy => :rootify

  attr_accessible :name,
                  :slug,
                  :price,
                  :description,
                  :quantity,
                  :available,
                  :in_stock,
                  :packaging_type,
                  :scientific_name,
                  :recommendations,
                  :parent_id

  validates_presence_of :name, :message => "Please enter a name"
  validates_presence_of :slug, :message => "Please enter a slug"

  has_many :orders

  def to_param
    "#{id}-#{name.downcase.split.join("-")}"
  end

  def truncated_descript
    stripped_descrip = Sanitize.clean(description.strip, Sanitize::Config::RESTRICTED).split
    (stripped_descrip.length > 12) ? (stripped_descrip[0..11].join(" ") + "...") : stripped_descrip.join(" ")
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  def index
    @products = Product.roots.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      flash[:notice] = "A new product has been created"
      redirect_to admin_products_path
    else
      flash[:error] = "There was a problem"
      render :action => :new
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.attributes = params[:product]
    if @product.save
      flash[:notice] = "The product has been updated"
      redirect_to admin_products_path
    else
      flash[:error] = "There was a problem updating this product"
      render :action => :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @browser_title = "All Products"
    @products = Product.roots.paginate(:page => params[:page], :per_page => 4).search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
    @browser_title = @product.name
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_summary.html.haml
%table.product-summary{:border => 3}
  %tr.product-info
    %td.coming-soon= image_tag("coming-soon.png", :alt => "Picture coming soon")
    %td
      %b= "Name:"
      %br
      #{product.name}
      %br
      %br
      %b= "Scientific Name:"
      %br
      - sci_name = product.scientific_name.present? ? product.scientific_name : "None"
      #{sci_name}
  %tr.description
    %td{:colspan => 2}
      != "#{product.truncated_descript}"
      %br
      = link_to "Click here to see more", product_path(product)

app/views/products/index.html.haml
%section.products
  %h1="Our Products"

  - if @products.present?
    .search
      = form_tag(products_path, :method => 'get') do
        = text_field_tag :search, params[:search], :placeholder => "Enter Product Name"
        .button
          = submit_tag("Search")
          
    = will_paginate @products
    - @products.each do |product|
      = render :partial => "product_summary", :locals => {:product => product}
  - else
    = "Sorry, there are no results to show"

app/views/products/show.html.haml
%section.products

  .full-product
    %h1= "Information on #{@product.name}"
    .info
      = image_tag("coming-soon-full.png", :alt => "Picture coming soon")

      %div.overview
        %b= "Product:"
        #{@product.name}
        %br
        - unless @product.scientific_name.blank?
          %b= "Scientific Name:"
          #{@product.scientific_name}

    .description
      %h3= "Description:"
      != @product.description
      %br
      %br
      %h3= "This product is available in the following types:"
      %table{:border => "3"}
        %tr
          %th="Name"
          %th="Packaging Type"
          %th="Price"
          %th="Status"
          %th
        - @product.children.each do |prod|
          %tr
            %td.name= prod.name
            %td.packaging= prod.packaging_type
            %td.price= number_to_currency(prod.price)
            %td
              %b= (prod.in_stock ? "In Stock" : "Out of Stock")
            %td= link_to (current_user.blank? ? "Order Now" : "Add to Cart"), sign_in_carts_path(:product_id => prod.id)
            